In [43]:
import pandas as pd
import numpy as np
import tensorflow as tf
#from keras.utils import to_categorical

In [76]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [77]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [78]:
df.Species.nunique()

3

In [79]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
df["Species"] = lb.fit_transform(df["Species"])
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [85]:
X = df.iloc[:, 1:5].values
y1 = df.iloc[:, -1].values

In [86]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [87]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [89]:
from sklearn.preprocessing import OneHotEncoder
z=y1.reshape(-1, 1)
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(z)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [90]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [91]:
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

In [92]:
model.compile(optimizer='sgd', loss='categorical_crossentropy',
              metrics=['acc'])

In [93]:
model.fit(X, y, epochs=200)

Epoch 1/200
5/5 [==============================] - 0s 2ms/step - loss: 1.9661 - acc: 0.3133
Epoch 2/200
5/5 [==============================] - 0s 2ms/step - loss: 1.3845 - acc: 0.3400
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 1.0970 - acc: 0.3267
Epoch 4/200
5/5 [==============================] - 0s 2ms/step - loss: 0.9271 - acc: 0.3600
Epoch 5/200
5/5 [==============================] - 0s 2ms/step - loss: 0.8543 - acc: 0.4933
Epoch 6/200
5/5 [==============================] - 0s 2ms/step - loss: 0.8161 - acc: 0.7067
Epoch 7/200
5/5 [==============================] - 0s 2ms/step - loss: 0.8244 - acc: 0.7000
Epoch 8/200
5/5 [==============================] - 0s 2ms/step - loss: 0.8152 - acc: 0.6267
Epoch 9/200
5/5 [==============================] - 0s 2ms/step - loss: 0.7705 - acc: 0.7267
Epoch 10/200
5/5 [==============================] - 0s 2ms/step - loss: 0.7480 - acc: 0.7200
Epoch 11/200
5/5 [==============================] - 0s 1ms/step - loss: 0.7372 

5/5 [==============================] - 0s 3ms/step - loss: 0.1763 - acc: 0.9733
Epoch 89/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1926 - acc: 0.9467
Epoch 90/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1853 - acc: 0.9667
Epoch 91/200
5/5 [==============================] - ETA: 0s - loss: 0.1793 - acc: 0.937 - 0s 3ms/step - loss: 0.1814 - acc: 0.9667
Epoch 92/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1694 - acc: 0.9800
Epoch 93/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1700 - acc: 0.9733
Epoch 94/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1663 - acc: 0.9733
Epoch 95/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1700 - acc: 0.9733
Epoch 96/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1609 - acc: 0.9733
Epoch 97/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1905 - acc: 0.9467
Epoch 98/200
5/5 [===========================

5/5 [==============================] - 0s 3ms/step - loss: 0.1028 - acc: 0.9733
Epoch 176/200
5/5 [==============================] - 0s 2ms/step - loss: 0.1031 - acc: 0.9667
Epoch 177/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0972 - acc: 0.9733
Epoch 178/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1057 - acc: 0.9733
Epoch 179/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0970 - acc: 0.9667
Epoch 180/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1139 - acc: 0.9467
Epoch 181/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0972 - acc: 0.9800
Epoch 182/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0960 - acc: 0.9733
Epoch 183/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0977 - acc: 0.9733
Epoch 184/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0953 - acc: 0.9800
Epoch 185/200
5/5 [==============================] - 0s 2ms/step - loss: 0

In [94]:
from tensorflow import lite

In [95]:
converter = lite.TFLiteConverter.from_keras_model(model)

tfmodel = converter.convert()

open('iris.tflite', 'wb').write(tfmodel)

INFO:tensorflow:Assets written to: C:\Users\AYUSHR~1\AppData\Local\Temp\tmpvpzsupjo\assets


2536

In [59]:
from sklearn.datasets import load_iris
iris_data = load_iris() # load the iris dataset

In [60]:
print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [61]:
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

In [62]:
y_

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [64]:
# One Hot encode the class labels
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

In [66]:
# Split the data for training and testing
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.30)

In [67]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))


In [71]:
from tensorflow.keras.optimizers import Adam
# Adam optimizer with learning rate of 0.001
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


In [72]:
print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [73]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

Epoch 1/200
21/21 - 1s - loss: 1.1066 - accuracy: 0.3714
Epoch 2/200
21/21 - 0s - loss: 1.0615 - accuracy: 0.3810
Epoch 3/200
21/21 - 0s - loss: 1.0447 - accuracy: 0.3810
Epoch 4/200
21/21 - 0s - loss: 1.0280 - accuracy: 0.3905
Epoch 5/200
21/21 - 0s - loss: 1.0112 - accuracy: 0.5810
Epoch 6/200
21/21 - 0s - loss: 0.9908 - accuracy: 0.6762
Epoch 7/200
21/21 - 0s - loss: 0.9690 - accuracy: 0.6762
Epoch 8/200
21/21 - 0s - loss: 0.9444 - accuracy: 0.6762
Epoch 9/200
21/21 - 0s - loss: 0.9167 - accuracy: 0.6762
Epoch 10/200
21/21 - 0s - loss: 0.8848 - accuracy: 0.6762
Epoch 11/200
21/21 - 0s - loss: 0.8523 - accuracy: 0.6762
Epoch 12/200
21/21 - 0s - loss: 0.8180 - accuracy: 0.6762
Epoch 13/200
21/21 - 0s - loss: 0.7840 - accuracy: 0.6762
Epoch 14/200
21/21 - 0s - loss: 0.7472 - accuracy: 0.6762
Epoch 15/200
21/21 - 0s - loss: 0.7118 - accuracy: 0.6762
Epoch 16/200
21/21 - 0s - loss: 0.6790 - accuracy: 0.6762
Epoch 17/200
21/21 - 0s - loss: 0.6474 - accuracy: 0.6762
Epoch 18/200
21/21 - 0s

Epoch 142/200
21/21 - 0s - loss: 0.0973 - accuracy: 0.9810
Epoch 143/200
21/21 - 0s - loss: 0.0917 - accuracy: 0.9714
Epoch 144/200
21/21 - 0s - loss: 0.0935 - accuracy: 0.9619
Epoch 145/200
21/21 - 0s - loss: 0.0925 - accuracy: 0.9714
Epoch 146/200
21/21 - 0s - loss: 0.0930 - accuracy: 0.9714
Epoch 147/200
21/21 - 0s - loss: 0.0975 - accuracy: 0.9619
Epoch 148/200
21/21 - 0s - loss: 0.0927 - accuracy: 0.9810
Epoch 149/200
21/21 - 0s - loss: 0.0927 - accuracy: 0.9619
Epoch 150/200
21/21 - 0s - loss: 0.0953 - accuracy: 0.9714
Epoch 151/200
21/21 - 0s - loss: 0.0931 - accuracy: 0.9714
Epoch 152/200
21/21 - 0s - loss: 0.0919 - accuracy: 0.9714
Epoch 153/200
21/21 - 0s - loss: 0.0903 - accuracy: 0.9619
Epoch 154/200
21/21 - 0s - loss: 0.0907 - accuracy: 0.9619
Epoch 155/200
21/21 - 0s - loss: 0.0902 - accuracy: 0.9714
Epoch 156/200
21/21 - 0s - loss: 0.0895 - accuracy: 0.9619
Epoch 157/200
21/21 - 0s - loss: 0.0917 - accuracy: 0.9714
Epoch 158/200
21/21 - 0s - loss: 0.0943 - accuracy: 0.96

In [74]:
results = model.evaluate(test_x, test_y)

2/2 [==============================] - 0s 5ms/step - loss: 0.0484 - accuracy: 0.9778


In [75]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.048359
Final test set accuracy: 0.977778
